default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: ems_development

test:
  <<: *default
  database: ems_test

production:
  <<: *default
  database: ems_production
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  database: ems_production
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  database: ems_production
  url: <%= ENV["DATABASE_URL"] %>

cache:
  <<: *default
  database: ems_production
  url: <%= ENV["DATABASE_URL"] %>